---
name: Release

on:
  push:
    branches: ["main"]
    paths: ["charts/**/metadata.yaml"]

permissions:
  contents: read
  id-token: write
  packages: write

env:
  # Ref: https://github.com/container-registry/helm-charts-oci-proxy
  CHARTPROXY_URL: chartproxy.container-registry.com

jobs:
  changed-charts:
    name: Get Changed Files
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: charts/**/metadata.yaml

      - name: Extract Chart values
        id: charts
        env:
          FILTER: '[.]'
        run: |
          charts=$(yq eval-all --indent=0 --output-format=json "${FILTER}" \
              ${{ steps.changed-files.outputs.all_changed_and_modified_files }} \
          )
          echo "charts=${charts}" >> $GITHUB_OUTPUT

  push-charts:
    needs: changed-charts
    name: Push Charts
    runs-on: ubuntu-latest
    if: ${{ needs.changed-charts.outputs.charts != '[]' }}
    strategy:
      matrix:
        charts: ${{ fromJSON(needs.changed-charts.outputs.charts) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Variables
        run: |
          CHART_VERSION=${{ matrix.charts.version }}
          CHART_VERSION=${CHART_VERSION#v}
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: Push Chart
        run: |
          helm pull ${{ env.CHARTPROXY_URL }}/${{ matrix.charts.registry }}/${{ matrix.charts.chart }} --version ${CHART_VERSION}
          helm push ${{ matrix.charts.chart }}-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository }}/charts/${{ matrix.charts.chart }}:${CHART_VERSION}

      - name: Sign artifacts with Cosign
        run: cosign sign --yes ghcr.io/${{ github.repository }}/charts/${{ matrix.charts.chart }}:${CHART_VERSION}
